name: Manala

description: Manala

inputs:
  dir:
    description: Working directory
    required: false
    default: .

runs:
  using: composite
  steps:
    - name: Set up manala
      uses: manala/github-action-manala/setup@v1
    - name: Manala update
      uses: manala/github-action-manala/update@v1
      with:
        dir: ${{ inputs.dir }}
