name: Manala

description: Manala

inputs:
  directory:
    description: Directory
    required: false
    default: .

runs:
  using: composite
  steps:
    - name: Set up manala
      uses: manala/github-action-manala/setup@v1
    - name: Manala update
      uses: manala/github-action-manala/update@v1
      with:
        directory: ${{ inputs.directory }}
