name: Manala - Update

description: Manala - Update

inputs:
  directory:
    description: Directory
    required: false
    default: .

runs:
  using: composite
  steps:
    - name: Manala update
      shell: bash
      working-directory: ${{ inputs.directory }}
      run: |
        manala update
