name: Manala - Update

description: Manala - Update

inputs:
  dir:
    description: Working directory
    required: false
    default: .

runs:
  using: composite
  steps:
    - name: Manala update
      shell: bash
      working-directory: ${{ inputs.dir }}
      run: |
        manala update
